name: Unit Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              run: |
                  cd api.animedatabase.net
                  npm ci

            - name: Run unit tests
              run: |
                  cd api.animedatabase.net
                  npm test
